image: flowm/mbed-cli

variables:
  REPO_NAME: "gitlab.lrz.de/move-on/move-on_helium_sensors"
  DEPLOY_HOST: "192.168.152.10"
  DEPLOY_PORT: "40106"
  DEPLOY_USER: "deploy"
  DEPLOY_TARGET: "${DEPLOY_USER}@${DEPLOY_HOST}"

before_script:
  - cd $CI_PROJECT_DIR
  # SSH Agent for deploy
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -p ${DEPLOY_PORT} ${DEPLOY_HOST} >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git submodule sync --recursive
  - git submodule update --init --recursive


stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cd src
    - make clean
    - make artifacts
  cache:
    paths:
      - mbed-os/
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA:0:8}"
    expire_in: 4 week
    paths:
      - artifacts/
  except:
    - rpi

deploy-sens:
  stage: deploy
  script:
    - scp -P ${DEPLOY_PORT} artifacts/move-on_helium_sensors.hex ${DEPLOY_TARGET}:move-on_helium_sensors.hex
    - ssh -p ${DEPLOY_PORT} ${DEPLOY_TARGET} "st-flash --format ihex write move-on_helium_sensors.hex"
    - timeout --preserve-status --foreground 30 ssh -p ${DEPLOY_PORT} ${DEPLOY_TARGET} "mqttserial" || true
  except:
    - rpi

deploy-rpi:
  stage: deploy
  script:
    - ssh -p ${DEPLOY_PORT} ${DEPLOY_TARGET} "cd /opt/move-on_helium/SEN/ && git fetch && git reset --hard origin/rpi && tools/grafana/daemon/setup.sh"
  only:
    - rpi
